### ISSUE TITLE
clang-format on debian unrecognized

### ISSUE THREAD

**Issue by aganm** [mikr/whatstyle#7]
I'm trying to use whatstyle on debian with clang-format but I'm getting this error

```
Unknown formatter type clang-format Debian clang-format version 11.0.1-2
Currently only these formatters are supported: clang-format, yapf, uncrustify, astyle, indent, tidy, scalariform, scalafmt, rfmt, rustfmt
```

I'm not sure what to do to fix this. Any idea?

**Comment by mikr** [comment]
It's funny. All of the dozen or so formatters report an identifiable string prefix given the --version parameter, like so:
```
$ clang-format --version
clang-format version 11.1.0
```

But of all Linux distributions and all other operating systems Debian is the only one that finds it useful to stick their distro name into the version output of clang-format.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```
```
$ clang-format --version
Debian clang-format version 11.0.1-2
```

To fix this issue please look for this [code fragment](https://github.com/mikr/whatstyle/blob/eff02bfa45a75019ad4e470085ff7c4da51cb5c4/whatstyle.py#L6600) in whatstyle.py:
`('clang-format', ClangFormatter),`

and insert the following line below it:
`('Debian clang-format', ClangFormatter),`

"Debian clang-format" is then recognized and whatstyle hopefully works for you.
I won't add this to whatstyle though because it is needless breakage that should be
fixed by Debian.

**Comment by aganm** [comment]
Thanks!
